version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'javascript'
      # kodiak `merge.automerge_label`
      - 'automerge'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      npm-security:
        applies-to: security-updates
        patterns: ['*']
      npm-minor-patch:
        applies-to: version-updates
        patterns: ['*']
        update-types: ['minor', 'patch']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'github_actions'
      # kodiak `merge.automerge_label`
      - 'automerge'
    groups:
      github-actions:
        patterns: ['*']
